### ISSUE TITLE
Doplňanie popisu pri vytváraní vydajov a píjmov

### ISSUE THREAD

**Issue by Adman1724** [michalfalat/CFC#15]
Nezobrazí sa vyskakovacie okno  pri vytváraní vydaju alebo príjmu

**Comment by michalfalat** [comment]
autocompete na   zobrazenie uz pouzitych popisov v systeme

**Comment by michalfalat** [comment]
pridat filtrovanie

**Comment by michalfalat** [comment]
filrovanie pridane do v1.0.2
