### ISSUE TITLE
Prehlad príjmov/výdajov upraviť zobrazenie - mobilna verzia

### ISSUE THREAD

**Issue by Adman1724** [michalfalat/CFC#17]
Upraviť zobrazenie na mobilnej verzii prehľadu prijmov a vydajov  skor dropdown pre viacej informaciji a zakladne informacie nechať zobrazene ako datum a sumu  ostatne umiestiť do drop downu  aby uživatel nemusel scrolovať doprava a dolava

**Comment by michalfalat** [comment]
upravene do rozbalovacieho boxu
